#!/usr/bin/env bash
# =============================================================================
# apply-plugins.sh — deterministic plugin compiler
# =============================================================================
#
# Reads the `plugins` array from autoducks.json (the enablement contract
# defined by plugin.schema.json's $defs.enablementEntry), resolves/validates
# each package's plugin.json manifest, and regenerates every lowered
# artifact idempotently:
#
#   1. Aggregator workflow-hook actions at
#        .github/actions/autoducks/<agent>-<stage>/action.yml
#      for every hook point at least one plugin (or the relocated local
#      contribution) targets.
#   2. Per-agent compiled Claude settings at
#        .autoducks/providers/llm/claude/compiled/<agent>.settings.json
#   3. Per-agent plugin tool-grant deltas at
#        .autoducks/providers/llm/claude/compiled/<agent>.allowed-tools
#
# Zero plugins ⇒ no artifacts are written and the script exits 0.
#
# USAGE
#   bash .autoducks/core/config/apply-plugins.sh [--output-root DIR]
#
# CHECK / DRY-RUN MODE
#   Set AUTODUCKS_APPLY_PLUGINS_OUTPUT_ROOT=<dir> (or pass --output-root DIR,
#   which sets the same variable) to compute every artifact under <dir>
#   instead of clobbering the committed files, mirroring the real repo-
#   relative paths underneath it (e.g. <dir>/.github/actions/autoducks/...).
#   This is the interface the setup sync-check recomputes-and-diffs against.
#   Ownership checks (refuse-to-touch) still read the REAL committed files,
#   since dry-run mode reflects what a real run would do to the live tree.
#
# It is fully idempotent: every artifact is regenerated wholesale from
# config each run, so running it twice produces byte-identical output.
# =============================================================================

set -euo pipefail

die() { echo "apply-plugins: $*" >&2; exit 1; }

if ! command -v jq &>/dev/null; then
  die "jq is required but not installed"
fi

# ── Locate .autoducks root / repo root (mirrors load-config.sh) ────────────
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_dir="$_SCRIPT_DIR"
_depth=0
AUTODUCKS_ROOT=""
while [[ "$_depth" -lt 10 ]]; do
  if [[ -f "$_dir/autoducks.json" ]]; then
    AUTODUCKS_ROOT="$_dir"
    break
  fi
  _dir="$(dirname "$_dir")"
  (( _depth++ )) || true
done
[[ -n "$AUTODUCKS_ROOT" ]] || die "could not find autoducks.json"
REPO_ROOT="$(dirname "$AUTODUCKS_ROOT")"
CONFIG="$AUTODUCKS_ROOT/autoducks.json"
[[ -f "$CONFIG" ]] || die "$CONFIG not found"

# shellcheck source=/dev/null
source "$_SCRIPT_DIR/semver.sh"

# ── Args / dry-run output root (pinned interface for the sync check) ───────
OUTPUT_ROOT="${AUTODUCKS_APPLY_PLUGINS_OUTPUT_ROOT:-}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-root)
      shift
      [[ $# -gt 0 ]] || die "--output-root requires an argument"
      OUTPUT_ROOT="$1"
      ;;
    *)
      die "unrecognized argument '$1'"
      ;;
  esac
  shift
done

GENERATED_HEADER="# GENERATED BY autoducks apply-plugins.sh — DO NOT EDIT"

# ── Output helpers ───────────────────────────────────────────────────────
# All writes/removes are relative to REPO_ROOT unless OUTPUT_ROOT is set, in
# which case they land under OUTPUT_ROOT instead — the committed tree is
# never touched in dry-run mode.
_target_path() { # $1 = repo-relative path
  if [[ -n "$OUTPUT_ROOT" ]]; then
    printf '%s/%s' "$OUTPUT_ROOT" "$1"
  else
    printf '%s/%s' "$REPO_ROOT" "$1"
  fi
}

write_output_file() { # $1 = repo-relative path; content on stdin
  local rel="$1" dest
  dest="$(_target_path "$rel")"
  mkdir -p "$(dirname "$dest")"
  cat > "$dest"
}

# write_or_remove REL — write stdin to REL, unless stdin is empty/blank, in
# which case any existing artifact at REL is removed instead (no artifact
# for an empty delta, per the allowed-tools file-format contract).
write_or_remove() {
  local rel="$1" dest content
  content="$(cat)"
  dest="$(_target_path "$rel")"
  if [[ -z "$content" ]]; then
    rm -f "$dest"
  else
    mkdir -p "$(dirname "$dest")"
    printf '%s\n' "$content" > "$dest"
  fi
}

remove_output_file() { # $1 = repo-relative path
  rm -f "$(_target_path "$1")"
}

sha256_of() { # content on stdin
  if command -v sha256sum &>/dev/null; then
    sha256sum | awk '{print $1}'
  else
    shasum -a 256 | awk '{print $1}'
  fi
}

# ── Valid enum sets (mirrors plugin.schema.json $defs) ──────────────────────
ALL_AGENTS=(architect engineer developer reviewer fix resolver rework defer product agent)
ALL_AGENTS_SPACE="${ALL_AGENTS[*]}"
HOOK_POINTS=(
  agent-pre agent-post
  architect-pre architect-post
  close-pre close-post
  defer-pre defer-post
  developer-pre developer-post
  engineer-pre engineer-post
  fix-pre fix-post
  maestro-pre maestro-post
  product-pre product-post
  resolver-pre resolver-post
  revert-pre revert-post
  reviewer-pre reviewer-post
  rework-pre rework-post
)

is_valid_agent() { local a; for a in "${ALL_AGENTS[@]}"; do [[ "$a" == "$1" ]] && return 0; done; return 1; }
is_valid_hook_point() { local h; for h in "${HOOK_POINTS[@]}"; do [[ "$h" == "$1" ]] && return 0; done; return 1; }

# ── Source resolution ────────────────────────────────────────────────────
resolve_source() { # $1 = name, $2 = source → prints resolved local dir
  local name="$1" source="$2"
  case "$source" in
    ./*)
      local d="$REPO_ROOT/${source#./}"
      [[ -d "$d" ]] || die "plugin '$name': local path '$source' not found"
      printf '%s' "$d"
      ;;
    .autoducks/plugins/*)
      local d="$REPO_ROOT/$source"
      [[ -d "$d" ]] || die "plugin '$name': vendored path '$source' not found"
      printf '%s' "$d"
      ;;
    github:*)
      local rest="${source#github:}"
      [[ "$rest" == *@* ]] || die "plugin '$name': github source '$source' missing required @ref"
      local ownerrepo="${rest%@*}" ref="${rest##*@}"
      [[ "$ownerrepo" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || die "plugin '$name': malformed github source '$source'"
      if [[ ! "$ref" =~ ^[0-9a-fA-F]{40}$ ]]; then
        die "plugin '$name': floating ref '$ref' refused — pin 'github:' sources to a full 40-character commit SHA"
      fi
      local dest="$REPO_ROOT/.autoducks/plugins/$name"
      command -v git &>/dev/null || die "plugin '$name': git is required to fetch github: sources"
      if [[ ! -d "$dest/.git" ]]; then
        git clone --quiet "https://github.com/$ownerrepo.git" "$dest" || die "plugin '$name': failed to clone $ownerrepo"
      fi
      ( cd "$dest" && git fetch --quiet --depth 1 origin "$ref" && git checkout --quiet "$ref" ) \
        || die "plugin '$name': failed to fetch/checkout ref '$ref'"
      printf '%s' "$dest"
      ;;
    registry:*)
      die "plugin '$name': registry: sources are not yet supported"
      ;;
    *)
      die "plugin '$name': unrecognized source form '$source'"
      ;;
  esac
}

# ── Manifest validation (field-by-field, per plugin.schema.json) ───────────
validate_manifest() { # $1 = resolved dir, $2 = declared enablement name
  local dir="$1" declared_name="$2" manifest="$1/plugin.json"
  [[ -f "$manifest" ]] || die "plugin '$declared_name': plugin.json not found at $dir"
  jq empty "$manifest" 2>/dev/null || die "plugin '$declared_name': plugin.json is not valid JSON"

  local sv name ver
  sv="$(jq -r '.schemaVersion // empty' "$manifest")"
  [[ "$sv" == "1" ]] || die "plugin '$declared_name': schemaVersion must be 1"

  name="$(jq -r '.name // empty' "$manifest")"
  [[ -n "$name" ]] || die "plugin '$declared_name': manifest missing 'name'"
  [[ "$name" =~ ^[a-z0-9-]+$ ]] || die "plugin '$declared_name': manifest 'name' is not kebab-case"
  [[ "$name" == "$declared_name" ]] || die "plugin '$declared_name': manifest name '$name' does not match plugins[] entry name"

  ver="$(jq -r '.version // empty' "$manifest")"
  [[ "$ver" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]] || die "plugin '$declared_name': manifest 'version' is not valid semver"

  local hp
  for hp in $(jq -r '.hooks // [] | .[]' "$manifest"); do
    is_valid_hook_point "$hp" || die "plugin '$declared_name': invalid hook point '$hp' in manifest"
    [[ -f "$dir/hooks/$hp/action.yml" ]] || die "plugin '$declared_name': declares hook '$hp' but hooks/$hp/action.yml is missing"
  done

  local tg
  for tg in $(jq -r '.targets // [] | .[]' "$manifest"); do
    is_valid_agent "$tg" || die "plugin '$declared_name': invalid target agent '$tg' in manifest"
  done

  # Cross-validate declared mcpServers/claudeHooks against claude/mcp.json
  # and claude/hooks.json (plugin.schema.json:76-90) — a declared name/event
  # with no matching entry (or vice versa) is a diagnostic, not a silent gap.
  local mcpsrv mcpf="$dir/claude/mcp.json"
  for mcpsrv in $(jq -r '.mcpServers // [] | .[]' "$manifest"); do
    { [[ -f "$mcpf" ]] && jq -e --arg n "$mcpsrv" '(.mcpServers // {}) | has($n)' "$mcpf" >/dev/null; } \
      || die "plugin '$declared_name': manifest declares mcpServers '$mcpsrv' but claude/mcp.json has no matching entry"
  done
  if [[ -f "$mcpf" ]]; then
    for mcpsrv in $(jq -r '.mcpServers // {} | keys[]' "$mcpf"); do
      jq -e --arg n "$mcpsrv" '(.mcpServers // []) | index($n) != null' "$manifest" >/dev/null \
        || die "plugin '$declared_name': claude/mcp.json defines server '$mcpsrv' but manifest 'mcpServers' does not declare it"
    done
  fi

  local hookev hooksf="$dir/claude/hooks.json"
  for hookev in $(jq -r '.claudeHooks // [] | .[]' "$manifest"); do
    { [[ -f "$hooksf" ]] && jq -e --arg e "$hookev" '(.hooks // {}) | has($e)' "$hooksf" >/dev/null; } \
      || die "plugin '$declared_name': manifest declares claudeHooks '$hookev' but claude/hooks.json has no matching entry"
  done
  if [[ -f "$hooksf" ]]; then
    for hookev in $(jq -r '.hooks // {} | keys[]' "$hooksf"); do
      jq -e --arg e "$hookev" '(.claudeHooks // []) | index($e) != null' "$manifest" >/dev/null \
        || die "plugin '$declared_name': claude/hooks.json defines event '$hookev' but manifest 'claudeHooks' does not declare it"
    done
  fi
}

# ── Config validation against configSchema (field-by-field, not a full
# JSON-Schema engine — mirrors the rest of the shell-based loader stack) ───
validate_config() { # $1 = configSchema json (or empty/null), $2 = config json, $3 = plugin name
  local schema="$1" config="$2" pname="$3"
  [[ -z "$schema" || "$schema" == "null" ]] && return 0

  local r
  for r in $(jq -r '.required // [] | .[]' <<<"$schema"); do
    jq -e --arg k "$r" 'has($k)' <<<"$config" >/dev/null \
      || die "plugin '$pname': config missing required field '$r'"
  done

  local k ptype ctype
  for k in $(jq -r '.properties // {} | keys[]' <<<"$schema"); do
    jq -e --arg k "$k" 'has($k)' <<<"$config" >/dev/null || continue
    ptype="$(jq -r --arg k "$k" '.properties[$k].type // empty' <<<"$schema")"
    [[ -z "$ptype" ]] && continue
    [[ "$ptype" == "integer" ]] && ptype="number"
    ctype="$(jq -r --arg k "$k" '.[$k] | type' <<<"$config")"
    [[ "$ctype" == "$ptype" ]] || die "plugin '$pname': config.$k expected type '$ptype', got '$ctype'"
  done
}

# ── autoducksVersion compat gate (advisory-only when host has no version) ──
check_version_compat() { # $1 = host version (may be empty), $2 = plugin constraint (may be empty), $3 = plugin name
  local host="$1" constraint="$2" pname="$3"
  [[ -z "$host" || -z "$constraint" ]] && return 0

  semver::satisfies "$host" "$constraint" && return 0
  local status=$?
  if [[ "$status" -eq 2 ]]; then
    die "plugin '$pname': malformed autoducksVersion '$constraint'"
  fi
  die "plugin '$pname': requires autoducksVersion '$constraint', host is '$host'"
}

# ── Load + validate the plugins[] enablement array ──────────────────────────
# autoducks.json.version is an optional consumer override for testing a gate;
# .autoducks/VERSION is the normal source. No stamping — this only reads.
HOST_VERSION="$(jq -r '.version // empty' "$CONFIG")"
if [[ -z "$HOST_VERSION" && -f "$AUTODUCKS_ROOT/VERSION" ]]; then
  HOST_VERSION="$(tr -d '[:space:]' < "$AUTODUCKS_ROOT/VERSION")"
fi
PLUGIN_COUNT="$(jq '.plugins // [] | length' "$CONFIG")"

PLUGIN_NAMES=()
declare -A PLUGIN_DIR=() PLUGIN_TARGETS=() PLUGIN_HOOKS=()

for ((_i = 0; _i < PLUGIN_COUNT; _i++)); do
  entry="$(jq -c ".plugins[$_i]" "$CONFIG")"
  name="$(jq -r '.name // empty' <<<"$entry")"
  source="$(jq -r '.source // empty' <<<"$entry")"
  config="$(jq -c '.config // {}' <<<"$entry")"

  [[ "$name" =~ ^[a-z0-9-]+$ ]] || die "plugins[$_i]: invalid or missing 'name'"
  [[ -n "$source" ]] || die "plugin '$name': missing 'source'"
  [[ -z "${PLUGIN_DIR[$name]:-}" ]] || die "duplicate plugin name '$name' in plugins[]"

  dir="$(resolve_source "$name" "$source")"
  validate_manifest "$dir" "$name"
  manifest="$dir/plugin.json"

  validate_config "$(jq -c '.configSchema // empty' "$manifest")" "$config" "$name"
  check_version_compat "$HOST_VERSION" "$(jq -r '.autoducksVersion // empty' "$manifest")" "$name"

  if jq -e '(.targets // []) | length == 0' "$manifest" >/dev/null; then
    targets="$ALL_AGENTS_SPACE"
  else
    targets="$(jq -r '.targets | join(" ")' "$manifest")"
  fi
  hooks="$(jq -r '.hooks // [] | join(" ")' "$manifest")"

  PLUGIN_NAMES+=("$name")
  PLUGIN_DIR["$name"]="$dir"
  PLUGIN_TARGETS["$name"]="$targets"
  PLUGIN_HOOKS["$name"]="$hooks"
done

plugin_has_hook() { [[ " ${PLUGIN_HOOKS[$1]} " == *" $2 "* ]]; }
plugin_targets_agent() { [[ " ${PLUGIN_TARGETS[$1]} " == *" $2 "* ]]; }

# ── 1. Aggregator workflow-hook actions ─────────────────────────────────────
render_aggregator_body() { # $1 = hook point, remaining = contributors ("@local" or plugin name)
  local point="$1"; shift
  printf "name: 'autoducks plugin aggregator: %s'\n" "$point"
  printf "description: 'Aggregated plugin hook contributions for %s'\n" "$point"
  printf 'runs:\n  using: '"'"'composite'"'"'\n  steps:\n'
  local c step_name step_uses pdir prel
  for c in "$@"; do
    if [[ "$c" == "@local" ]]; then
      step_name="local"
      step_uses="./.autoducks/plugins/@local/hooks/$point"
    else
      step_name="plugin: $c"
      pdir="${PLUGIN_DIR[$c]}"
      prel="${pdir#"$REPO_ROOT"/}"
      step_uses="./$prel/hooks/$point"
    fi
    # Forwards the full hand-authored-hook environment contract (see
    # guides/customization#environment-contract), including the per-agent
    # extras (BASE_BRANCH, IS_PR, AGENT_OUTCOME, COMMENT_ISSUE_NUM, DRY_RUN)
    # that only some agents/stages set — forwarding an unset var is a no-op.
    cat <<STEP
    - name: '$step_name'
      uses: $step_uses
      env:
        AUTODUCKS_AGENT: \${{ env.AUTODUCKS_AGENT }}
        AUTODUCKS_STAGE: \${{ env.AUTODUCKS_STAGE }}
        ISSUE_NUM: \${{ env.ISSUE_NUM }}
        REPO: \${{ env.REPO }}
        COMMENT_ID: \${{ env.COMMENT_ID }}
        RUN_ID: \${{ env.RUN_ID }}
        COMMENTER: \${{ env.COMMENTER }}
        GH_TOKEN: \${{ env.GH_TOKEN }}
        BASE_BRANCH: \${{ env.BASE_BRANCH }}
        IS_PR: \${{ env.IS_PR }}
        AGENT_OUTCOME: \${{ env.AGENT_OUTCOME }}
        COMMENT_ISSUE_NUM: \${{ env.COMMENT_ISSUE_NUM }}
        DRY_RUN: \${{ env.DRY_RUN }}
STEP
  done
}

for point in "${HOOK_POINTS[@]}"; do
  contributors=()
  [[ -f "$REPO_ROOT/.autoducks/plugins/@local/hooks/$point/action.yml" ]] && contributors+=("@local")
  for name in "${PLUGIN_NAMES[@]}"; do
    plugin_has_hook "$name" "$point" && contributors+=("$name")
  done

  rel=".github/actions/autoducks/$point/action.yml"
  real="$REPO_ROOT/$rel"

  if [[ "${#contributors[@]}" -eq 0 ]]; then
    # No plugin contributes here. Leave a hand-authored hook untouched; clean
    # up a now-orphaned generated aggregator so repeated runs stay idempotent.
    if [[ -f "$real" ]] && head -n1 "$real" | grep -qF "$GENERATED_HEADER"; then
      remove_output_file "$rel"
    fi
    continue
  fi

  if [[ -f "$real" ]] && ! head -n1 "$real" | grep -qF "$GENERATED_HEADER"; then
    die "hook point '$point' has a hand-authored action at $rel that a plugin also targets — relocate it into .autoducks/plugins/@local/hooks/$point/ before enabling plugins for this hook point (never auto-migrated)"
  fi

  body="$(render_aggregator_body "$point" "${contributors[@]}")"
  hash="$(printf '%s' "$body" | sha256_of)"
  {
    printf '%s\n' "$GENERATED_HEADER"
    printf '# content-hash: %s\n' "$hash"
    printf '%s' "$body"
  } | write_output_file "$rel"
done

# ── 2 & 3. Compiled Claude settings + allowed-tools delta, per agent ───────
for agent in "${ALL_AGENTS[@]}"; do
  targeting=()
  for name in "${PLUGIN_NAMES[@]}"; do
    plugin_targets_agent "$name" "$agent" && targeting+=("$name")
  done

  compiled_rel=".autoducks/providers/llm/claude/compiled/$agent.settings.json"
  tools_rel=".autoducks/providers/llm/claude/compiled/$agent.allowed-tools"

  if [[ "${#targeting[@]}" -eq 0 ]]; then
    remove_output_file "$compiled_rel"
    remove_output_file "$tools_rel"
    continue
  fi

  result_file="$(mktemp)"
  base="$REPO_ROOT/.autoducks/providers/llm/claude/settings.json"
  if [[ -f "$base" ]]; then cp "$base" "$result_file"; else echo '{}' > "$result_file"; fi

  # seen_mcp / seen_env track only *plugin* contributions (never the base
  # settings.json) — a plugin is free to override a base-defined mcpServers
  # entry or env value (layered on top of the base, per plugins.mdx's
  # "Ordering & conflict semantics"); conflict detection exists solely to
  # catch two plugins disagreeing with each other.
  declare -A seen_mcp=()
  declare -A seen_env=()

  tools_file="$(mktemp)"
  : > "$tools_file"

  for name in "${targeting[@]}"; do
    pdir="${PLUGIN_DIR[$name]}"

    mcpf="$pdir/claude/mcp.json"
    if [[ -f "$mcpf" ]]; then
      for nm in $(jq -r '.mcpServers // {} | keys[]' "$mcpf"); do
        [[ -n "${seen_mcp[$nm]:-}" ]] && die "agent '$agent': duplicate MCP server name '$nm' — plugin '$name' conflicts with an earlier plugin contributor (a plugin may freely override an MCP server already defined in the base settings.json; only plugin-vs-plugin collisions hard-fail)"
        seen_mcp["$nm"]=1
        val="$(jq -c --arg n "$nm" '.mcpServers[$n]' "$mcpf")"
        jq --arg n "$nm" --argjson v "$val" '.mcpServers[$n] = $v' "$result_file" > "$result_file.tmp" && mv "$result_file.tmp" "$result_file"
      done
    fi

    hooksf="$pdir/claude/hooks.json"
    if [[ -f "$hooksf" ]]; then
      for ev in $(jq -r '.hooks // {} | keys[]' "$hooksf"); do
        arr="$(jq -c --arg e "$ev" '.hooks[$e]' "$hooksf")"
        jq --arg e "$ev" --argjson a "$arr" '.hooks[$e] = ((.hooks[$e] // []) + $a)' "$result_file" > "$result_file.tmp" && mv "$result_file.tmp" "$result_file"
      done
    fi

    patchf="$pdir/claude/settings.patch.json"
    if [[ -f "$patchf" ]]; then
      jq -e 'has("model")' "$patchf" >/dev/null \
        && die "agent '$agent': plugin '$name' settings.patch.json sets 'model' — rejected, plugins may not override model"

      if jq -e '(.permissions.allow // []) | length > 0' "$patchf" >/dev/null; then
        arr="$(jq -c '.permissions.allow' "$patchf")"
        jq --argjson a "$arr" '.permissions.allow = (((.permissions.allow // []) + $a) | unique)' "$result_file" > "$result_file.tmp" && mv "$result_file.tmp" "$result_file"
      fi
      if jq -e '(.permissions.deny // []) | length > 0' "$patchf" >/dev/null; then
        arr="$(jq -c '.permissions.deny' "$patchf")"
        jq --argjson a "$arr" '.permissions.deny = (((.permissions.deny // []) + $a) | unique)' "$result_file" > "$result_file.tmp" && mv "$result_file.tmp" "$result_file"
      fi

      if jq -e '(.env // {}) | length > 0' "$patchf" >/dev/null; then
        while IFS=$'\t' read -r k v; do
          [[ -z "$k" ]] && continue
          if [[ -n "${seen_env[$k]:-}" && "${seen_env[$k]}" != "$v" ]]; then
            die "agent '$agent': conflicting env.$k — plugin '$name' sets a different value than an earlier plugin contributor (a plugin may freely override an env value already set in the base settings.json; only plugin-vs-plugin collisions hard-fail)"
          fi
          seen_env["$k"]="$v"
        done < <(jq -r '.env | to_entries[] | [.key, (.value|tostring)] | @tsv' "$patchf")
        envobj="$(jq -c '.env' "$patchf")"
        jq --argjson e "$envobj" '.env = ((.env // {}) * $e)' "$result_file" > "$result_file.tmp" && mv "$result_file.tmp" "$result_file"
      fi

      # mcpServers/hooks are excluded here even though this is a JSON
      # merge-patch: those keys have dedicated conflict-checked channels
      # (claude/mcp.json, claude/hooks.json) and must not reach the compiled
      # settings via a silent last-writer-wins / array-replace through
      # settings.patch.json instead.
      rest="$(jq -c 'del(.model, .permissions, .env, .mcpServers, .hooks)' "$patchf")"
      if [[ "$rest" != "{}" ]]; then
        jq --argjson p "$rest" '. * $p' "$result_file" > "$result_file.tmp" && mv "$result_file.tmp" "$result_file"
      fi
    fi

    while IFS= read -r t; do [[ -n "$t" ]] && echo "$t" >> "$tools_file"; done \
      < <(jq -r '.allowedTools // [] | .[]' "$pdir/plugin.json")
  done

  jq -S '.' "$result_file" | write_output_file "$compiled_rel"
  sort -u "$tools_file" | write_or_remove "$tools_rel"

  rm -f "$result_file" "$tools_file"
  unset seen_mcp seen_env
done

exit 0
